[theme]
primaryColor = "#4287f5"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#e6eaf3"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[global]
developmentMode = false 